required_review_count: 2
changes_threshold: 100
status_url: 'https://github.com/apps/minimun-reviews'
ready_message: 'No pending reviews'
not_ready_message: 'Pending review approvals'
not_ready_state: 'pending'
