name: Check priority labels

on:
  workflow_dispatch:
#   schedule:
#   - cron: "5 * * * *"

jobs:
  priority_zero_issues_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'P0'
        days-before-stale: 1
        days-before-close: 99
        stale-issue-message: 'Stale issue message'

  priority_one_issues_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'P1'
        days-before-stale: 7
        days-before-close: 99
        stale-issue-message: 'Stale issue message'
